### ISSUE TITLE
How to control the size of the hash?

### ISSUE THREAD

**Issue by adambuczynski** [intervalia/gulp-hash-filename#2]
For example, my files are named as: 

```
lib-1.0.0.min.35edb5bab21540fc163febf4982d9ce4.js
```

I would like to be able to specify to only use for example 8 characters of the hash:

```
lib-1.0.0.min.35edb5ba.js
```

Something like this?

```
format: '{{hash:8}}'
```

**Comment by intervalia** [comment]
Resolved in release 1.1.0

**Comment by adambuczynski** [comment]
Excellent, thank you

**Comment by intervalia** [comment]
Does the fix do what you need?

**Comment by adambuczynski** [comment]
Yes works like a charm, thank you.
