### ISSUE TITLE
Different hash on different machine

### ISSUE THREAD

**Issue by paramsingh88** [intervalia/gulp-hash-filename#4]
I'm trying to create a content based hash but the one generated on my local machine is not the same as on my staging server or any other machine. I want it to be consistent and machine independent.

**Comment by intervalia** [comment]
Would you send me some examples?

Take any text file, nothing important to you, and generate a hashed filename version of the file on your local machine and on other machines. Then email me all of the different files. But I need the actual files so I can figure out what is causing this.

Let me know which machine (OS & version) gulp version and any other info that might help me derive the problem.

For example how do you get the files from your local machine to the other machines? Git, Subversion, Thumb drive, etc.

Send the examples to: intervalia@gmail.com

**Comment by intervalia** [comment]
If no one else is having the problem and I can't get sample, failing, code then I will close this issue.
