### ISSUE TITLE
getDateStr bug: when file atime/ctime/mtime is not available, error occur

### ISSUE THREAD

**Issue by tangshuang** [intervalia/gulp-hash-filename#5]
In lib/performHash.js, it use getDateStr(file.stat.atime) to get date string.
However, file.stat.atime sometimes comes to be undefined in my case when I using console.log.
Could you please fix this?

**Comment by intervalia** [comment]
The current expectation is to throw an error when a Date object is not passed in.

If not an exception then what would you expect to be returned?

**Comment by tangshuang** [comment]
In fact, I want it to be silent without any notice or error.
I have tested the plugin, and sometimes it works well.
After it throw an error which breaks process, I have to wait for your fix and removed it from my project.
Thanks for your reply, and I will try it again if a updated version published.

**Comment by intervalia** [comment]
Resolved in Version 2.0.1
